-- RBTR · PSNM outreach target seeds
-- Auto-generated from ~/Desktop/psnm/leads/*.csv
-- 205 unique prospects (deduped by company+postcode)

INSERT INTO psnm_outreach_targets (company, city, postcode, industry, website, email) VALUES
  ('ABI Electronics Ltd', 'Barnsley', 'S75 2BY', 'Electronics Manufacturing', 'abielectronics.co.uk', NULL),
  ('Newell & Wright Transport', 'Sheffield', 'S9 1XH', 'Haulage & Logistics', 'nwtransport.com', 'traffic@nwtransport.com'),
  ('4S Distribution', 'Rotherham', 'S60 1DJ', 'Storage & Distribution', '4sdistribution.co.uk', NULL),
  ('Pricecheck Pharmaceuticals', 'Rotherham', 'S63 7QY', 'FMCG Wholesale & Distribution', 'pricecheck.co.uk', NULL),
  ('AJ Webb and Sons', 'Sheffield', 'S2 5BQ', 'Fresh Produce Wholesale', 'ajwebb.co.uk', NULL),
  ('International Stones (UK) Ltd', 'Rotherham', 'S60 1AE', 'Stone Importer & Wholesale', 'istones.co.uk', NULL),
  ('Gripple Ltd', 'Sheffield', 'S9 1DA', 'Manufacturing - Wire Products', 'gripple.com', NULL),
  ('Yorkshire Manufacturing Limited', 'Brighouse', 'HD6 2QH', 'Metal Manufacturing', 'ymlimited.co.uk', 'sales@ymlimited.co.uk'),
  ('Clugston Distribution Services', 'Scunthorpe', 'DN16 1HX', 'Logistics & Distribution', 'clugston.co.uk', NULL),
  ('Bowker Transport', 'Doncaster', 'DN3 3FE', 'FMCG Logistics & Haulage', 'bowkertransport.co.uk', 'enquiries@bowkergroup.co.uk'),
  ('Renoco Engineering Ltd', 'Chesterfield', 'S41 9EY', 'Steel Fabrication & Engineering', 'renocoeng.com', 'renocoeng@aol.com'),
  ('Premier Precision Engineering Ltd', 'Chesterfield', 'S41 8NA', 'Precision Engineering', 'premierprecisionengineeringltd.co.uk', NULL),
  ('Futaba Manufacturing UK Ltd', 'Derby', 'DE65 5BT', 'Automotive Manufacturing', 'fmuk.ltd', NULL),
  ('PPS Ltd', 'Alfreton', 'DE55 7RA', 'Industrial Equipment Supply', 'pps-ltd.co.uk', NULL),
  ('Denby Pottery Company', 'Denby', 'DE5 8NX', 'Ceramics Manufacturing', 'denby.co.uk', NULL),
  ('Bidfood Nottingham', 'Langley Mill', 'NG16 4HY', 'Food & Drink Wholesale', 'bidfood.co.uk', NULL),
  ('MKG Foods', 'Nottingham', 'NG2 4AA', 'Food Service Distribution', 'mkgfoods.co.uk', NULL),
  ('All Shires Foods Ltd', 'Nottingham', 'NG1 5FT', 'Food Manufacturing & Distribution', 'allshiresfoods.co.uk', NULL),
  ('GCL Food Ingredients', 'Nottingham', 'NG18 2AH', 'Food Ingredients Manufacturing', 'gclfoodingredients.com', NULL),
  ('Oakdale Manufacturing', 'Nottingham', 'NG7 2PX', 'Screw & Fastener Manufacturing', 'oakdalemanufacturing.co.uk', NULL),
  ('Howarth Wholesale', 'Doncaster', 'DN5 8TU', 'Food & Drink Wholesale', 'howarthwholesale.co.uk', NULL),
  ('BigFish Brand', 'Grimsby', 'DN31 3RD', 'Seafood Food Manufacturing', 'bigfishbrand.co.uk', NULL),
  ('JCS Fish', 'Grimsby', 'DN31 1RN', 'Seafood Processing & Distribution', 'jcsfish.co.uk', 'info@jcsfish.co.uk'),
  ('South Lincs Foodservice', 'Boston', 'PE21 8NY', 'Food Service Distribution', 'southlincsfoodservice.co.uk', NULL),
  ('Spaldings Limited', 'Lincoln', 'LN6 3XJ', 'Agricultural Parts Distribution', 'spaldings.co.uk', 'emarketing@spaldings.co.uk'),
  ('Blackburn Starling (RSE Control Systems)', 'Nottingham', 'NG2 3AY', 'Electrical Manufacturing', 'blackburn-starling.co.uk', NULL),
  ('Premier Quality Foods', 'Kinsley', 'WF9 5JB', 'Food Wholesale & Distribution', 'premierqualityfoods.com', NULL),
  ('Stanton Logistics', 'Stanton', 'DE7 4QP', 'Warehousing & Logistics', 'stantonlogistics.co.uk', NULL),
  ('Yorkshire Logistics Group', 'Sheffield', 'S4 7QA', 'Road Haulage & Logistics', 'yorkshirelogisticsgroup.com', NULL),
  ('VLT Logistics', 'Leeds (South Yorks routes)', 'LS11 5AL', 'Transport & Warehousing', 'vltlogistics.co.uk', NULL),
  ('Swann Morton Ltd', 'Sheffield', 'S6 2BJ', 'Medical Device Manufacturing', 'swannmorton.com', NULL),
  ('Bridon International', 'Doncaster', 'DN5 8TU', 'Steel Wire & Rope Manufacturing', 'bridon-bekaert.com', NULL),
  ('Sheffield Forgemasters', 'Sheffield', 'S9 2LX', 'Steel Forging & Engineering', 'sheffieldforgemasters.com', NULL),
  ('AESSEAL plc', 'Rotherham', 'S60 1DX', 'Mechanical Seals Manufacturing', 'aesseal.com', NULL),
  ('Pegler Yorkshire Group', 'Doncaster', 'DN4 5JQ', 'Plumbing & Heating Manufacturing', 'pegleryorkshire.co.uk', NULL),
  ('R McDowell Transport', 'Sheffield', 'S9 4WU', 'Road Haulage & Warehousing', 'rmcdowell.co.uk', NULL),
  ('Intamarque Wholesale', 'Batley (serves Yorks)', 'WF17 9AX', 'FMCG Wholesale Distribution', 'intamarquewholesale.com', NULL),
  ('Bulmers of Chesterfield', 'Chesterfield', 'S40 1SN', 'FMCG Distribution', 'bulmersofc.co.uk', NULL),
  ('Thorntons (Ferrero UK)', 'Alfreton', 'DE55 4HF', 'Confectionery Manufacturing', 'thorntons.co.uk', NULL),
  ('Rolls-Royce Precision Casting', 'Derby', 'DE24 8BJ', 'Aerospace Manufacturing', 'rolls-royce.com', NULL),
  ('JCB Components', 'Uttoxeter (Derbyshire border)', 'ST14 5JP', 'Heavy Equipment Manufacturing', 'jcb.com', NULL),
  ('Lindum Group', 'Lincoln', 'LN6 3RE', 'Construction & Logistics', 'lindumgroup.co.uk', NULL),
  ('Portland Larder', 'Mansfield', 'NG18 4AH', 'Food & Drink Producer', 'portlandlarder.co.uk', NULL),
  ('Nottingham Trent Meats', 'Nottingham', 'NG7 3GZ', 'Meat Processing & Distribution', 'nottinghamtrentmeats.co.uk', NULL),
  ('East Midlands Food', 'Derby', 'DE1 2WT', 'Food Distribution & Logistics', 'eastmidlandsfood.co.uk', NULL),
  ('AF Blakemore & Son', 'Doncaster (depot)', 'DN3 1HH', 'FMCG Distribution (Spar)', 'afblakemore.co.uk', NULL),
  ('Bestway Wholesale Sheffield', 'Sheffield', 'S9 1XA', 'Cash & Carry Wholesale', 'bestwaywholesale.co.uk', NULL),
  ('Yorkshire Tea (Taylors of Harrogate)', 'Sheffield (distribution)', 'S4 7PE', 'Drinks Manufacturing & Distribution', 'yorkshiretea.co.uk', NULL),
  ('Cleckheaton Packaging', 'Cleckheaton (W Yorks border)', 'BD19 5LH', 'Packaging Manufacturing', 'cleckheatonpackaging.co.uk', NULL),
  ('Meadow Foods', 'Chester (Yorks depots)', 'CH1 4QR', 'Dairy Manufacturing & Distribution', 'meadowfoods.co.uk', NULL),
  ('Test Company Ltd', 'Sheffield', 'S9 1XA', 'Manufacturing', 'testcompany.co.uk', 'info@testcompany.co.uk'),
  ('Acme Distribution', 'Rotherham', 'S60 1DX', 'Distribution', 'acmedist.co.uk', NULL),
  ('WKH Group', 'Leeds / South Yorks', 'LS12 6HH', 'Plastic Engineering & Machining', 'wkhgroup.co.uk', 'enquiries@wkhgroup.co.uk'),
  ('GW Engineering', 'Barnsley', 'S70 3JG', 'Metal Engineering & Fabrication', 'gw-engineering.co.uk', 'graeme@gw-engineering.co.uk'),
  ('Building Materials Yorkshire Ltd', 'Yorkshire', 'LS1 4DY', 'Building Materials Distribution', 'buildingmaterialsyorkshire.co.uk', 'sales@buildingmaterialsyorkshire.co.uk'),
  ('Sleaford Quality Foods', 'Sleaford', 'NG34 7EH', 'Food Manufacturing', 'sleafordqf.com', 'enquiries@sleafordqf.com'),
  ('Fosse Healthcare', 'Derby', 'DE1 2RJ', 'Healthcare Supplies & Staffing', 'fossehealthcare.co.uk', NULL),
  ('Medequip Derby City', 'Derby', 'DE23 8YJ', 'Medical Equipment Distribution', 'medequip-uk.com', 'derbycity@medequip-uk.com'),
  ('Masons Foodservice', 'Leicester (covers Derbys)', 'LE8 6JW', 'Food Service Distribution', 'masonfoods.co.uk', NULL),
  ('All Shires Foods Ltd', 'Nottingham', 'NG6 8YP', 'Food Manufacturing & Distribution', 'allshiresfoods.co.uk', NULL),
  ('Drink Warehouse UK', 'Sheffield', 'S9 1XA', 'Wholesale Alcohol Distribution', 'drinkwarehouseuk.co.uk', NULL),
  ('South Yorkshire Truss Supplies', 'Doncaster', 'DN5 8TU', 'Timber Roof Truss Manufacturing', 'sytrusssupplies.co.uk', NULL),
  ('J S Construction', 'Lincoln', 'LN5 7SE', 'Construction & Civil Engineering', 'jsconstruction.builders', NULL),
  ('Jarvale Construction', 'South Yorkshire', 'S25 3QF', 'Specialist Construction', 'jarvale.co.uk', NULL),
  ('Tata Steel UK', 'Rotherham', 'S60 1DW', 'Steel Manufacturing', 'tatasteeleurope.com', NULL),
  ('Outokumpu Stainless', 'Sheffield', 'S9 1XH', 'Stainless Steel Manufacturing', 'outokumpu.com', NULL),
  ('Dormer Sandvik', 'Sheffield', 'S25 3QD', 'Cutting Tools Manufacturing', 'dormerpramet.com', NULL),
  ('LUK UK Ltd', 'Rotherham', 'S60 1AX', 'Automotive Components Manufacturing', 'schaeffler.com', NULL),
  ('Sheffield Insulations Group', 'Sheffield', 'S9 1XG', 'Insulation Distribution', 'sheffield-insulations.co.uk', NULL),
  ('NM Metal Recycling', 'Kinsley', 'WF9 5JB', 'Metal Recycling & Processing', 'nmmetalrecycling.co.uk', 'info@nmmetalrecycling.co.uk'),
  ('J West Engineering', 'Barnsley', 'S70 3JG', 'Civil & Structural Engineering', 'theconstructionindex.co.uk', NULL),
  ('Farla Medical Healthcare', 'Nottingham', 'NG1 6DQ', 'Medical Equipment Supply', 'farlamedicalhealthcare.com', NULL),
  ('Lincoln Health Supply', 'Lincoln', 'LN5 7AA', 'Healthcare Products Distribution', 'lincolnhealthsupply.com', NULL),
  ('Boeing Sheffield', 'Sheffield', 'S9 1XH', 'Aerospace Components Manufacturing', 'boeing.com', NULL),
  ('Cammell Laird / Forging', 'Sheffield', 'S4 7QA', 'Heavy Forging & Engineering', 'sheffieldforgemasters.com', NULL),
  ('Newburgh Engineering', 'Rotherham', 'S66 8HS', 'Precision Engineering', 'newburgh.co.uk', NULL),
  ('Sandvik Coromant', 'Sheffield', 'S25 3QD', 'Cutting Tools & Tooling Systems', 'sandvik.coromant.com', NULL),
  ('Sertus Manufacturing', 'Barnsley', 'S71 1AY', 'Metal Components Manufacturing', 'sertus.co.uk', NULL),
  ('Speciality Steels (Liberty)', 'Rotherham', 'S60 1DW', 'Specialty Steel Manufacturing', 'libertysteelgroup.com', NULL),
  ('Luxus', 'Lincolnshire', 'LN11 9UG', 'Sustainable Plastics Manufacturing', 'luxus.co.uk', 'info@luxus.co.uk'),
  ('Bplas', 'Lincoln', 'LN6 3XJ', 'Plastics Compounding', 'bplas.com', NULL),
  ('Lindum Packaging', 'Lincoln', 'LN6 3RE', 'Packaging Manufacturing', 'lindumgroup.co.uk', NULL),
  ('Joseph Gleave & Son', 'South Yorkshire', 'S73 8AQ', 'Horticultural Products Manufacturing', 'gleave.co.uk', NULL),
  ('D Wharfe & Sons', 'Doncaster', 'DN5 8TH', 'Agricultural Supplies Distribution', 'wharfe.co.uk', NULL),
  ('United Malt', 'Lincolnshire', 'LN5 7SE', 'Malt Processing & Distribution', 'unitedmalt.com', NULL),
  ('Quorn Foods', 'Lincolnshire (Belasis)', 'TS23 4EA', 'Food Manufacturing', 'quorn.co.uk', NULL),
  ('Lincoln Packaging', 'Lincoln', 'LN1 3AL', 'Corrugated Packaging Manufacturing', 'lincolnpackaging.co.uk', NULL),
  ('Sharp''s Bedrooms', 'Rotherham', 'S66 8XH', 'Furniture Manufacturing', 'sharpsbedrooms.com', NULL),
  ('Maltby Mining Museum', 'Rotherham (industrial heritage site — network contact)', 'S66 7JU', 'Community Organisation', 'maltbymining.org.uk', NULL),
  ('Notts Industries', 'Nottingham', 'NG8 6PX', 'Industrial Equipment Manufacturing', 'nottsindustries.co.uk', NULL),
  ('East Midlands Coatings', 'Derby', 'DE1 3JU', 'Industrial Coatings & Surface Finishing', 'emcoatings.co.uk', NULL),
  ('Derbyshire Aggregates', 'Matlock', 'DE4 3AG', 'Quarry & Aggregates Distribution', 'derbyshireaggregates.co.uk', NULL),
  ('Blaze Manufacturing', 'Chesterfield', 'S40 2WG', 'Fire Safety Equipment Manufacturing', 'blazemanufacturing.co.uk', NULL),
  ('RPC Superfos', 'Grantham', 'NG31 7XQ', 'Plastic Packaging Manufacturing', 'rpc-superfos.com', NULL),
  ('Monarch Chemicals', 'Huddersfield (distributes Yorks)', 'HD5 9UY', 'Chemical Distribution', 'monarchchemicals.co.uk', NULL),
  ('Bell Flavors & Fragrances', 'South Yorkshire', 'S9 1XB', 'Flavour & Fragrance Manufacturing', 'bellff.com', NULL),
  ('Samuel Taylor Ltd', 'Sheffield', 'S9 1AB', 'Metal Presswork & Stampings', 'samueltaylor.co.uk', NULL),
  ('Autogreen', 'Rotherham', 'S66 8HS', 'Tyre Distribution & Wholesale', 'autogreen.co.uk', NULL),
  ('Steel Protection Consulting', 'Rotherham', 'S60 2AF', 'Corrosion Protection Products', 'steelprotection.co.uk', NULL),
  ('Associated British Foods (Silver Spoon)', 'Newark', 'NG24 2JF', 'Sugar & Food Manufacturing', 'abfoods.com', NULL),
  ('Bakkavor Group', 'Lincolnshire', 'NG23 6HE', 'Fresh Prepared Food Manufacturing', 'bakkavor.com', NULL),
  ('Greencore', 'Lincolnshire', 'NG34 7AB', 'Convenience Food Manufacturing', 'greencore.com', NULL),
  ('Cargill UK (Lincoln)', 'Lincoln', 'LN6 9BX', 'Agricultural Commodity Processing', 'cargill.co.uk', NULL),
  ('Linpac Packaging', 'Lincolnshire', 'LN11 9UG', 'Food Packaging Manufacturing', 'linpac.com', NULL),
  ('Anglian Water (supply chain)', 'Lincoln', 'LN5 7QA', 'Utilities Infrastructure & Supply Chain', 'anglianwater.co.uk', NULL),
  ('Amey plc (infrastructure)', 'Sheffield', 'S1 2JX', 'Infrastructure Services & Logistics', 'amey.co.uk', NULL),
  ('Kier Group (infrastructure)', 'Sheffield', 'S9 1XH', 'Construction & Infrastructure', 'kier.co.uk', NULL),
  ('Aggregate Industries', 'Lincolnshire', 'LN5 7SE', 'Aggregates & Building Materials', 'aggregate.com', NULL),
  ('Hanson UK (cement/aggregates)', 'Derbyshire', 'S42 6EN', 'Building Materials Manufacturing', 'hanson.com', NULL),
  ('Millward Brown', 'Rotherham', 'S60 1DG', 'Market Research & Storage', 'millwardbrown.com', NULL),
  ('Metalex Ltd', 'Sheffield', 'S9 2LX', 'Sheet Metal Fabrication', 'metalex.co.uk', NULL),
  ('Phoenix Scientific Industries', 'Nottingham', 'NG7 2GX', 'Scientific Instrument Manufacturing', 'psi-ware.com', NULL),
  ('Walkers Snack Foods (depot)', 'Chesterfield', 'S41 9EY', 'Food (Snacks) Distribution', 'walkers.co.uk', NULL),
  ('Weetabix (distribution centre)', 'Lincoln', 'LN5 7AA', 'Breakfast Cereal Distribution', 'weetabix.co.uk', NULL),
  ('Kerry Foods UK', 'Nottingham', 'NG2 4AA', 'Food Ingredients Manufacturing', 'kerry.com', NULL),
  ('Princes Foods (Lincolnshire)', 'Lincolnshire', 'LN1 3AL', 'Canned Food Manufacturing', 'princesgroup.com', NULL),
  ('Müller UK (dairy depot)', 'Derby', 'DE24 8BJ', 'Dairy Products Manufacturing', 'mullermilkingredients.co.uk', NULL),
  ('Co-op Food (distribution)', 'Sheffield', 'S9 1XA', 'Food Retail Distribution', 'co-operative.coop', NULL),
  ('Premier Foods (depot)', 'Sheffield', 'S4 7QA', 'Branded Food Distribution', 'premierfoods.co.uk', NULL),
  ('Molson Coors (distribution)', 'Burton / Midlands (covers Yorks)', 'DE14 1JZ', 'Brewing & Beverages Distribution', 'molsoncoors.com', NULL),
  ('Coca-Cola (distribution depot)', 'Sheffield', 'S9 1XH', 'Beverages Distribution', 'coca-cola.co.uk', NULL),
  ('Heinz (distribution)', 'Wigan / covers Yorks', 'WN3 4AZ', 'Food Distribution', 'heinz.co.uk', NULL),
  ('Unilever Iceam (depot)', 'Leeds / Yorks', 'LS12 6HH', 'FMCG Distribution', 'unilever.com', NULL),
  ('McBride plc', 'Middleton (covers Yorks)', 'M24 1LQ', 'Household Products Manufacturing', 'mcbride.co.uk', NULL),
  ('Reckitt (distribution)', 'Nottingham', 'NG2 1HL', 'FMCG Healthcare Distribution', 'reckitt.com', NULL),
  ('Johnson & Johnson MedTech', 'Sheffield', 'S9 1XB', 'Medical Device Distribution', 'jnj.com', NULL),
  ('Norgine Pharmaceuticals', 'Harefield (depot Yorks)', 'UB9 6NS', 'Pharmaceutical Distribution', 'norgine.com', NULL),
  ('Alliance Healthcare (depot)', 'Doncaster', 'DN3 1HH', 'Pharmaceutical & Medical Distribution', 'alliance-healthcare.co.uk', NULL),
  ('Bunzl Healthcare', 'Nottingham', 'NG2 3AA', 'Medical Consumables Distribution', 'bunzl.com', NULL),
  ('Paragon Medical', 'Nottingham', 'NG7 2GX', 'Medical Device Manufacturing', 'paragon-med.com', NULL),
  ('Mettler-Toledo', 'Sheffield', 'S9 1XA', 'Precision Weighing Equipment', 'mt.com', NULL),
  ('Hydratight', 'Rotherham', 'S66 8HS', 'Industrial Bolting & Tooling', 'hydratight.com', NULL),
  ('Castleton Technology', 'Rotherham', 'S60 1DX', 'Technology Hardware Distribution', 'castletontech.co.uk', NULL),
  ('Trackwork International', 'Rotherham', 'S60 2AF', 'Rail Track Manufacturing', 'trackwork.co.uk', NULL),
  ('Sheffield City Trust', 'Sheffield', 'S9 2LX', 'Leisure & Events (requires event storage)', 'sheffieldcitytrust.org', NULL),
  ('Rockingham Motor Speedway', 'Corby (Midlands border)', 'NN17 5AF', 'Motorsport Venue (merchandise storage)', 'rockingham.co.uk', NULL),
  ('Doncaster Rovers FC', 'Doncaster', 'DN4 5HT', 'Football Club (merchandise/event storage)', 'doncasterroversfc.co.uk', NULL),
  ('Barnsley FC', 'Barnsley', 'S71 1ET', 'Football Club (merchandise/event storage)', 'barnsleyfc.co.uk', NULL),
  ('Rotherham United FC', 'Rotherham', 'S60 1AH', 'Football Club (merchandise/event storage)', 'themillers.co.uk', NULL),
  ('Heron Foods', 'East Yorkshire (covers Dons)', 'HU1 1RQ', 'FMCG Retail & Distribution', 'heronfoods.com', NULL),
  ('Dee Bee Wholesale', 'Hull (delivers Yorks)', 'HU1 2AA', 'Cash & Carry Wholesale', 'deebeewholesale.co.uk', NULL),
  ('Aldi UK (regional depot)', 'Sheffield', 'S9 1XH', 'Grocery Retail Distribution', 'aldi.co.uk', NULL),
  ('Lidl UK (distribution)', 'Doncaster', 'DN3 3FE', 'Grocery Retail Distribution', 'lidl.co.uk', NULL),
  ('Toolstation (distribution)', 'Barnsley', 'S71 1AY', 'Trade Tools Distribution', 'toolstation.com', NULL),
  ('Screwfix (distribution)', 'Rotherham', 'S66 8HS', 'Trade Hardware Distribution', 'screwfix.com', NULL),
  ('Travis Perkins (depot)', 'Sheffield', 'S9 2LX', 'Builders Merchant & Distribution', 'travisperkins.co.uk', NULL),
  ('Jewson (depot)', 'Doncaster', 'DN3 1HH', 'Builders Merchant & Distribution', 'jewson.co.uk', NULL),
  ('Wolseley UK (depot)', 'Sheffield', 'S9 1XA', 'Plumbing & Heating Distribution', 'wolseley.co.uk', NULL),
  ('Speedy Hire', 'Rotherham', 'S60 1DG', 'Plant & Equipment Hire', 'speedyhire.co.uk', NULL),
  ('Brandon Hire', 'Sheffield', 'S9 2LX', 'Equipment Hire & Storage', 'brandonhire.co.uk', NULL),
  ('Sunbelt Rentals', 'Doncaster', 'DN3 3FE', 'Equipment Rental & Logistics', 'sunbeltrentals.co.uk', NULL),
  ('Sika Limited', 'Derby', 'DE24 8BJ', 'Construction Chemicals Manufacturing', 'sika.com', NULL),
  ('Bostik UK', 'Derby', 'DE24 8BJ', 'Adhesives & Sealants Manufacturing', 'bostik.com', NULL),
  ('RPM International (Rust-Oleum depot)', 'Sheffield', 'S9 1XA', 'Coatings & Sealants Distribution', 'rustoleum.co.uk', NULL),
  ('WD-40 Company (distribution)', 'Nottingham', 'NG2 4AA', 'Maintenance Products Distribution', 'wd40.co.uk', NULL),
  ('Cranswick Country Foods', 'Barnsley', 'S70 1RZ', 'Food Manufacturer', 'www.cranswick.plc.uk', NULL),
  ('Doncaster Foodservice', 'Doncaster', 'DN1 3BU', 'Food Distributor', 'www.doncfoodservice.co.uk', NULL),
  ('William Jackson Food Group', 'Scunthorpe', 'DN15 8QY', 'Food Manufacturer', 'www.williamjacksonfoodgroup.co.uk', NULL),
  ('Holdsworth Confectionery', 'Halifax (Doncaster depot)', 'DN4 5JP', 'Food Manufacturer', 'www.holdsworthchocolates.co.uk', NULL),
  ('Spar UK Distribution (Shirebrook)', 'Shirebrook', 'NG20 8RY', 'FMCG Distributor', 'www.spar.co.uk', NULL),
  ('Booker Wholesale Sheffield', 'Sheffield', 'S9 1DA', 'FMCG Wholesaler', 'www.booker.co.uk', NULL),
  ('Nisa Retail (Scunthorpe DC)', 'Scunthorpe', 'DN15 8XF', 'FMCG Wholesaler', 'www.nisaretail.com', NULL),
  ('Central England Co-op (Ilkeston DC)', 'Ilkeston', 'DE7 8HW', 'FMCG Distributor', 'www.centralengland.coop', NULL),
  ('Jacksons Bakery', 'Lincoln', 'LN6 3QT', 'Food Manufacturer', 'www.jacksonsbakery.co.uk', NULL),
  ('Fletchers Bakeries', 'Sheffield', 'S9 2HS', 'Food Manufacturer', 'www.fletchersbakeries.co.uk', NULL),
  ('Walkers Snack Foods (Lincoln)', 'Lincoln', 'LN6 3LG', 'Food Manufacturer', 'www.walkers.co.uk', NULL),
  ('Pinguin Foods', 'Humber', 'DN31 2TF', 'Food Manufacturer', 'www.pinguinfoods.co.uk', NULL),
  ('Kepak Convenience Foods', 'Worksop', 'S80 2RJ', 'Food Manufacturer', 'www.kepak.com', NULL),
  ('Freshtime UK', 'Boston', 'PE21 8EQ', 'Food Manufacturer', 'www.freshtime.co.uk', NULL),
  ('Young''s Seafood', 'Grimsby', 'DN31 3SW', 'Food Manufacturer', 'www.youngsseafood.co.uk', NULL),
  ('Sealord Grofish', 'Grimsby', 'DN31 3SY', 'Food Manufacturer', 'www.sealord.com', NULL),
  ('Chilled Foods Humber (CFH)', 'Grimsby', 'DN32 0AT', 'Food Distributor', NULL, NULL),
  ('Total Produce (Doncaster)', 'Doncaster', 'DN5 8TU', 'Food Distributor', 'www.totalproduce.com', NULL),
  ('RH Amar (Midlands)', 'Nottingham', 'NG90 2JP', 'FMCG Distributor', 'www.rhamar.com', NULL),
  ('United Biscuits (Nottingham depot)', 'Nottingham', 'NG7 2SB', 'FMCG Distributor', 'www.unitedbiscuits.com', NULL),
  ('Fowler Welch (Spalding)', 'Spalding', 'PE11 3YR', 'Logistics / Cold Chain', 'www.fowlerwelch.co.uk', NULL),
  ('Norbert Dentressangle (now XPO - Scunthorpe)', 'Scunthorpe', 'DN15 8RF', 'Logistics', 'www.xpo.com', NULL),
  ('Wincanton Logistics (Worksop)', 'Worksop', 'S80 2BT', 'Logistics', 'www.wincanton.co.uk', NULL),
  ('Gregory Distribution (Doncaster)', 'Doncaster', 'DN4 8DE', 'Logistics', 'www.gregorydist.co.uk', NULL),
  ('Yusen Logistics (Nottingham)', 'Nottingham', 'NG90 1JT', 'Logistics', 'www.yusen-logistics.com', NULL),
  ('Sheffield Galvanizing', 'Sheffield', 'S9 3XA', 'Steel / Engineering', 'www.sheffieldgalvanizing.co.uk', NULL),
  ('Outokumpu Stainless', 'Sheffield', 'S9 2JH', 'Steel Manufacturer', 'www.outokumpu.com', NULL),
  ('Tata Steel Distribution', 'Rotherham', 'S60 1DW', 'Steel Distributor', 'www.tatasteeleurope.com', NULL),
  ('Atlas Copco (Sheffield)', 'Sheffield', 'S9 1XL', 'Industrial Equipment', 'www.atlascopco.com', NULL),
  ('Sandvik Coromant UK', 'Sheffield', 'S9 4WA', 'Engineering / Tooling', 'www.sandvik.coromant.com', NULL),
  ('Firth Rixson (now Arconic)', 'Sheffield', 'S9 2SU', 'Aerospace / Engineering', 'www.arconic.com', NULL),
  ('Aurora Process Solutions', 'Chesterfield', 'S41 8LH', 'Engineering', 'www.auroraprocesssolutions.com', NULL),
  ('Weightron Bilanciai', 'Dronfield', 'S18 2XN', 'Industrial Equipment', 'www.weightron.com', NULL),
  ('IMI Precision Engineering', 'Worksop', 'S80 2QS', 'Engineering', 'www.imiprecision.com', NULL),
  ('Harsco Environmental (Rotherham)', 'Rotherham', 'S60 1AG', 'Industrial Services', 'www.harsco.com', NULL),
  ('Travis Perkins (Doncaster)', 'Doncaster', 'DN2 4NJ', 'Construction Materials', 'www.travisperkins.co.uk', NULL),
  ('Jewson Builders Merchants (Sheffield)', 'Sheffield', 'S9 2WN', 'Construction Materials', 'www.jewson.co.uk', NULL),
  ('Saint-Gobain Building Distribution', 'Mansfield', 'NG18 2BY', 'Construction Materials', 'www.saint-gobain.co.uk', NULL),
  ('Tarmac Building Products (Lincolnshire)', 'Lincoln', 'LN6 0JS', 'Construction Materials', 'www.tarmac.com', NULL),
  ('Kilsaran International (Notts)', 'Newark', 'NG24 2ES', 'Construction Materials', 'www.kilsaran.co.uk', NULL),
  ('Brammer Buck & Hickman (Sheffield)', 'Sheffield', 'S9 5DQ', 'Industrial Distribution', 'www.buk.com', NULL),
  ('Cromwell Tools (Nottingham)', 'Nottingham', 'NG7 2UL', 'Industrial Distribution', 'www.cromwell.co.uk', NULL),
  ('RS Components (Corby / Notts DC)', 'Corby / Notts', 'NG90 5BH', 'Industrial Distribution', 'www.rs-online.com', NULL),
  ('Scunthorpe Pharmaceuticals / NorthLincs dispensary', 'Scunthorpe', 'DN16 1GF', 'Healthcare / Pharma', NULL, NULL),
  ('Mediline Supplies (Nottingham)', 'Nottingham', 'NG7 3FB', 'Medical / Healthcare Supply', NULL, NULL),
  ('Sodhexo Health (Sheffield)', 'Sheffield', 'S10 2JF', 'Healthcare Services', 'www.sodexo.com', NULL),
  ('Trent Valley Healthcare Supplies', 'Grantham', 'NG31 7XD', 'Healthcare / Pharma', NULL, NULL),
  ('Lindores Agriculture', 'Spalding', 'PE11 3AB', 'Agricultural Supplies', 'www.lindores.co.uk', NULL),
  ('Amenity Land Solutions', 'Lincoln', 'LN5 9NF', 'Agricultural / Groundcare Supplies', 'www.amenitylandsolutions.co.uk', NULL),
  ('Carr''s Billington Agriculture (Notts)', 'Newark', 'NG24 3BU', 'Agricultural Supplies', 'www.carrsbillington.com', NULL)
ON CONFLICT (company, postcode) DO NOTHING;
