-- 54_psnm_content_drafts.sql
-- RBTR content drafts table — stores AI-generated social posts for Ben's approval queue
-- Generated by /api/content/draft (vibe-based, Ben-voice, multi-platform)

create table if not exists psnm_content_drafts (
  id            uuid        primary key default gen_random_uuid(),
  source_event  text,                                                  -- workshop moment that triggered the draft
  photos        text[],                                                -- optional photo filenames/URLs
  vibe          text        check (vibe in (
                              'build-progress',
                              'behind-the-scenes',
                              'sponsor-shoutout',
                              'family',
                              'philosophy'
                            )),
  ig_short      text,                                                  -- IG caption <150 chars
  ig_medium     text,                                                  -- IG caption 3-5 sentences
  ig_long       text,                                                  -- IG caption 8-12 sentences
  yt_title      text,                                                  -- YouTube short/reel title
  yt_desc       text,                                                  -- YouTube short/reel description
  tiktok        text,                                                  -- TikTok caption
  status        text        not null default 'draft' check (status in (
                              'draft',
                              'approved',
                              'scheduled',
                              'posted',
                              'rejected'
                            )),
  created_at    timestamptz not null default now(),
  scheduled_at  timestamptz,
  posted_at     timestamptz
);

create index on psnm_content_drafts (status);
create index on psnm_content_drafts (created_at desc);
